// only include common ones
qid_unit_suffixes! {
    METRE => " m",
    KILOMETRE => " km",
    CENTIMETRE => " cm",
    MILLIMETRE => " mm",
    SQUARE_METRE => " m²",
    SQUARE_KILOMETRE => " km²",
    SQUARE_CENTIMETRE => " cm²",
    SQUARE_MILLIMETRE => " mm²",
    CUBIC_METRE => " m³",
    CUBIC_KILOMETRE => " km³",
    CUBIC_CENTIMETRE => " cm³",
    CUBIC_MILLIMETRE => " mm³",
    GRAM => " g",
    MILLIGRAM => " mg",
    KILOGRAM_PER_CUBIC_METRE => " kg/m³",
    GRAM_PER_CUBIC_CENTIMETRE => " g/cm³",
    MILLILITRE_PER_LITRE => " ml/l",
    MILLIGRAM_PER_CUBIC_METER => " mg/cm³",
    PARTS_PER_MILLION => " ppm",
    MILLIGRAM_PER_KILOGRAM => " mg/k",
    GRAM_PER_KILOGRAM => " g/kg",
    DEGREE_CELSIUS => " °C",
    KELVIN => " °K",
    DEGREE_FAHRENHEIT => " °F",
    KILOMETRE_PER_HOUR => " km/h",
    ASTRONOMICAL_UNIT => " AU",
    DEGREE => "°",
}
